### ISSUE TITLE
コメントの右クリック時の問題

### ISSUE THREAD

**Issue by mujurin1** [DaisukeDaisuke/MultiCommentViewer#12]
コメントを右クリックした時に以下の問題があります (１つのイシューで２つの問題を投稿してすみません)
a. 右クリックした項目がURLを含む場合フリーズする
b. 最初に右クリックした項目の内容で表示が固定されて２回目以降に別のコメントを右クリックしても内容が変わりません

b の問題があるため、最初に右クリックした項目が URL の場合に a の問題が発生してフリーズします

a については原因の箇所は `\MultiCommentViewer\ViewModels\MainViewModel.cs` の `GetUrlFromSelectedComment` 関数の正規表現のようです
現在の正規表現と (多分) 同じこちらの正規表現に変えると問題は起きませんでした
`Regex.Match(message, @"https?://[\w.-]+(?:/[\w./?%&=-]*)?");`

b については解決策が分かりませんでした。すみません。
解決出来ない場合は `\MultiCommentViewer\Views\CommentDataGrid.xaml` 65行目の `IsEnabled` を無くしても良いかもしれません
その場合にURLを含まないコメントで「URLを開く」を選択した場合にエラーが発生するため、
a で触れたのと同ファイル (`\MultiCommentViewer\ViewModels\MainViewModel.cs`) の `OpenUrl` 関数で `if (url == null) return;` のチェックが必要そうです

**Comment by mujurin1** [comment]
追記：新しい正規表現はグループ化してないので `match.Value` でURLだけを取り出せます

**Comment by DaisukeDaisuke** [comment]
fixed #13
